# Build Options
#  change yes to no to disable
#
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no	
EXTRAKEY_ENABLE = yes	
CONSOLE_ENABLE = no	
COMMAND_ENABLE = yes    
ENCODER_ENABLE = yes
NKRO_ENABLE = no        

BOOTLOADER = stm32duino
OPT_DEFS += -DBOOTLOADER_STM32DUINO
MCU_LDSCRIPT = STM32F103x6_stm32duino_bootloader
BOARD = STM32_F103_STM32DUINO
STM32_BOOTLOADER_ADDRESS = 0x80000000
DFU_ARGS = -d 1EAF:0003 -a 2 -R
DFU_SUFFIX_ARGS = -v 1EAF -p 0003
